CREATE TABLE Products (
    Id INT IDENTITY(1, 1) PRIMARY KEY,
    ProdName NVARCHAR(255) NOT NULL,
    ProdWeightG DECIMAL(10, 2) NOT NULL,
    ProdPricePer100G MONEY NOT NULL,
    CONSTRAINT UQ_ProductName UNIQUE (ProdName)
);
